### ISSUE TITLE
[TO DO] Database Structure

### ISSUE THREAD

**Issue by MTalhaAlkan** [barbayrak/RecommendationAPI#3]
Creating Database and models for movies @mehmetfatihgungor , @goktugberkulu and @MTalhaAlkan

**Comment by MTalhaAlkan** [comment]
NOTE: I tried different verions for mongodb dependency in pom.xml file and the version 3.0.4 works fine with +3 Mongo versions. Please sync with your projects with current version in order to get updated pom.xml file.

**Comment by goktugberkulu** [comment]
NOTE: To work with database, download the MovieLens data file at http://files.grouplens.org/datasets/movielens/ml-10m.zip and place its extracted files in the src folder of the project. Since the file size is too large, we could not push it to GitHub.

**Comment by mehmetfatihgungor** [comment]
The last bugs fixed on MongoConnector class and it works fine.
